authorName: default
experimentName: example_cifar10-network-morphism
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: pai
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    # for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 32
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 10
trial:
  command: python3 cifar10_keras.py
  codeDir: .
  gpuNum: 1
  cpuNum: 1
  memoryMB: 8196
  #The docker image to run nni job on pai
  image: msranni/nni:latest
  nniManagerNFSMountPath: {replace_to_your_nfs_mount_path}
  containerNFSMountPath: {replace_to_your_container_mount_path}
  paiStorageConfigName: {replace_to_your_storage_config_name}
paiConfig:
  #The username to login pai
  userName: username
  #The token to login pai
  token: token
  #The host of restful server of pai
  host: 10.10.10.10