authorName: unknown
experimentName: example_efficient_net
trialConcurrency: 8
maxExecDuration: 48h
maxTrialNum: 100
trainingServicePlatform: pai
searchSpacePath: search_net.json
useAnnotation: false
tuner:
  codeDir: .
  classFileName: tuner.py
  className: FixedProductTuner
  classArgs:
    product: 2
trial:
  codeDir: EfficientNet-PyTorch
  command: sh train_imagenet.sh
  cpuNum: 4
  memoryMB: 25000
  shmMB: 25000
  gpuNum: 1
  virtualCluster: nni
  image: msranni/nni:latest
  nniManagerNFSMountPath: /home/user/mnt
  containerNFSMountPath: /mnt/data/user
  paiStoraeConfigName: confignfs-data
nniManagerIp: <nni_manager_ip>
paiConfig:
  userName: <username>
  token: <token>
  host: <host>
