authorName: default
experimentName: example_mnist-keras
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 1
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: $HOME/.nni/examples/trials/mnist-keras/search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  tunerName: TPE
  #choice: Maximize, Minimize
  optimizationMode: Maximize
trial:
  trialCommand: python3 mnist-keras.py
  trialCodeDir: $HOME/.nni/examples/trials/mnist-keras
  trialGpuNum: 0