AUTO_RESUME: False
DATA_DIR: './data/imagenet'
MODEL: '604m_retrain'
RESUME_PATH: './experiments/workspace/retrain/resume.pth.tar'
SAVE_PATH: './'
SEED: 42
LOG_INTERVAL: 50
RECOVERY_INTERVAL: 0
WORKERS: 4
NUM_GPU: 2
SAVE_IMAGES: False
AMP: False
OUTPUT: 'None'
EVAL_METRICS: 'prec1'
TTA: 0
LOCAL_RANK: 0

DATASET:
  NUM_CLASSES: 1000
  IMAGE_SIZE: 224 # image patch size
  INTERPOLATION: 'random' # Image resize interpolation type
  BATCH_SIZE: 128 # batch size
  NO_PREFECHTER: False

NET:
  GP: 'avg'
  DROPOUT_RATE: 0.0
  SELECTION: 42

  EMA:
    USE: True
    FORCE_CPU: False # force model ema to be tracked on CPU
    DECAY: 0.9998

OPT: 'rmsproptf'
OPT_EPS: 1e-2
MOMENTUM: 0.9
DECAY_RATE: 0.1

SCHED: 'sgd'
LR_NOISE: None
LR_NOISE_PCT: 0.67
LR_NOISE_STD: 1.0
WARMUP_LR: 1e-4
MIN_LR: 1e-5
EPOCHS: 200
START_EPOCH: None
DECAY_EPOCHS: 30.0
WARMUP_EPOCHS: 3
COOLDOWN_EPOCHS: 10
PATIENCE_EPOCHS: 10
LR: 1e-2