searchSpaceFile: search_space.json
trialCommand: python3 mnist.py
trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 10
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: remote
  machineList:
    - host: ${your server's IP or domain name}
      user: ${your user name}
      ssh_key_file: ~/.ssh/id_rsa  # We recommend public key over password, it's more secure and convenient.
    # You can specify more than one SSH servers:
    - host: 123.123.123.123
      port: 10022
      user: nniuser
      password: 12345
      pythonPath: /usr/bin  # Other examples:
                            #   /opt/python3.9/bin
                            #   C:/Python39
                            #   C:/Users/USERNAME/.conda/envs/ENVNAME;C:/Users/USERNAME/.conda/envs/ENVNAME/Scripts;C:/Users/USERNAME/.conda/envs/ENVNAME/Library/bin
sharedStorage:
  storageType: AzureBlob
  localMountPoint: ${your/local/mount/point}
  remoteMountPoint: ${your/remote/mount/point}
  storageAccountName: ${replace_to_your_storageAccountName}
  storageAccountKey: ${replace_to_your_storageAccountKey}
  # If you did not set storageAccountKey, you need use `az login` with Azure CLI at first and set resourceGroupName.
  # resourceGroupName: ${replace_to_your_resourceGroupName}
  containerName: ${replace_to_your_containerName}
  # usermount means you have already mount this storage on localMountPoint
  # nnimount means nni will try to mount this storage on localMountPoint
  # nomount means storage will not mount in local machine, will support partial storages in the future 
  localMounted: nnimount