authorName: default
experimentName: example_mnist
trialConcurrency: 30
maxExecDuration: 8888888h
maxTrialNum: 9990
#choice: local, remote, pai
trainingServicePlatform: pai
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: ../tuner
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    batch_size: 30
trial:
  command: sh ./macro_cifar10_final.sh
  codeDir: .
  gpuNum: 2
  cpuNum: 4
  memoryMB: 32768
  #The docker image to run nni job on pai
  image: zejlin/nni:ir
  dataDir: hdfs://10.151.40.179:9286/quzha
  outputDir: hdfs://10.151.40.179:9286/quzha
  virtualCluster: nni
paiConfig:
  userName: quzha
  passWord: quzha123
  host: 10.151.40.179