authorName: default
experimentName: example_auto-gbdt
trialConcurrency: 1
maxExecDuration: 10h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: pai
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 0
  cpuNum: 1
  memoryMB: 8196
  #The docker image to run nni job on pai
  image: msranni/nni:latest
  nniManagerNFSMountPath: {replace_to_your_nfs_mount_path}
  containerNFSMountPath: {replace_to_your_container_mount_path}
  paiStorageConfigName: {replace_to_your_storage_config_name}
paiConfig:
  #The username to login pai
  userName: username
  #The token to login pai
  token: token
  #The host of restful server of pai
  host: 10.10.10.10