authorName: Unknown
experimentName: enas_macro
trialConcurrency: 4
maxExecDuration: 24h
maxTrialNum: 8
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: ../tuner
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    batch_size: 3

trial:
  command: sh ./macro_cifar10_final.sh
  codeDir: ./
  gpuNum: 1

